name: Run Specific Postman Collection Test

on:
  push:
    branches:
      - main
      
jobs:
  run-testcalc_ut:
    name: Run testcalc_ut.postman_collection
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 3. Run the specific Postman test
      - name: Run Postman Collection on testcalc_ut
        run: |
          newman run lab_8/tests/calc_ut.postman_collection.json \
            --reporters cli,junit \
            --reporter-junit-export lab_8/tests/test_results/calc_ut-report.xml
